### ISSUE TITLE
Go error: too many open files

### ISSUE THREAD

**Issue by ostiwe** [kubeshark/kubeshark#1265]
**Describe the bug**
After I run the command to view the traffic, an error occurs in the logs of the:
```
│ basenine 2022/12/04 12:35:30 Basenine Community (Version: 0.8.3)                                                                                                                                         │
│ basenine panic: too many open files                                                                                                                                                                      │
│ Stream closed EOF for kubeshark/kubeshark-api-server (kubeshark-api-server)                                                                                                                              │
│ basenine                                                                                                                                                                                                 │
│ basenine goroutine 1 [running]:                                                                                                                                                                          │
│ basenine github.com/up9inc/basenine/server/lib.Check(...)                                                                                                                                                │
│ basenine     /home/runner/work/basenine/basenine/server/lib/helpers.go:76                                                                                                                                │
│ basenine github.com/up9inc/basenine/server/lib/storages.NewNativeStorage(0x704501, 0x21, 0xc00021df38)                                                                                                   │
│ basenine     /home/runner/work/basenine/basenine/server/lib/storages/native.go:110 +0x130                                                                                                                │
│ basenine main.main()                                                                                                                                                                                     │
│ basenine     /home/runner/work/basenine/basenine/server/server.go:61 +0x51c                                                                                                                              │
│ Stream closed EOF for kubeshark/kubeshark-api-server (basenine)
```

**To Reproduce**
1. Run `kubeshark tab <pod name>` or `kubeshark tab -A`

**Expected behavior**
Correct launch

**Logs**
Terminal:
```
└─(15:39:02)──> ks tap --set dump-logs=true landing-7b44c76cb7-2jtkk                                                                                                                        ──(Sun,Dec04)─┘
Kubeshark will store up to 200MB of traffic, old traffic will be cleared once the limit is reached.
Tapping pods in namespaces "default"
Did not find any currently running pods that match the regex argument, kubeshark will automatically tap matching pods if any are created later. You can also try selecting a different namespace with -n or tap all namespaces with -A
Waiting for Kubeshark Agent to start...
E1204 15:39:16.407925   73424 portforward.go:406] an error occurred forwarding 8899 -> 8899: error forwarding port 8899 to pod e5aa96bd7bf1768e6feec27a6ebb38fa582b95983771bd730b7048340c3f1765, uid : failed to execute portforward in network namespace "/var/run/netns/cni-65ed13dd-861e-6df8-dab5-adb1372351b1": failed to connect to localhost:8899 inside namespace "e5aa96bd7bf1768e6feec27a6ebb38fa582b95983771bd730b7048340c3f1765", IPv4: dial tcp4 127.0.0.1:8899: connect: connection refused IPv6 dial tcp6 [::1]:8899: connect: connection refused
E1204 15:39:16.408416   73424 portforward.go:234] lost connection to pod
Couldn't connect to API server, for more info check logs at /Users/ostiwe/.kubeshark/kubeshark_cli.log
Error starting kubeshark tapper syncer: failed to get pods in ns: [default], context canceled
Kubeshark is available at http://localhost:8899
You can find the zip file with all logs in /Users/ostiwe/.kubeshark/kubeshark_logs_2022_12_04__15_39_18.zip

Removing kubeshark resources
```
kubeshark log: [kubeshark_logs_2022_12_04__15_47_04.zip](https://github.com/kubeshark/kubeshark/files/10148514/kubeshark_logs_2022_12_04__15_47_04.zip)

**Screenshots**
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/60335090/205491084-4591e8e7-b379-443c-a7fc-1ce6bea2a74a.png">
<img width="990" alt="image" src="https://user-images.githubusercontent.com/60335090/205491095-e0961499-4c42-4bd0-a6b0-e02d05cc7337.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Web Browser: Google Chrome

**Comment by mertyildiran** [comment]
Either for some reason the number file watchers increased in Basenine or your node had already too many open files. We will [migrate from Basenine to a PCAP-based storage](https://github.com/kubeshark/kubeshark/issues/1261) so this issue will be resolved.

**Comment by mertyildiran** [comment]
@ostiwe with [the latest stable release (38.1)](https://github.com/kubeshark/kubeshark/releases/tag/38.1) this issue should be fixed.
