### ISSUE TITLE
error message (hub is down / worker are down)

### ISSUE THREAD

**Issue by mothercow-dev** [kubeshark/kubeshark#1305]
Hi, 

I want to use kubeshark, but it is not possible due to an issue.

An error occurred (hub is down / worker are down)

<img width="1363" alt="스크린샷 2023-01-25 오후 3 54 57" src="https://user-images.githubusercontent.com/83107898/214501289-e2c9bf69-85ab-4628-b963-99ec7d96382e.png">

Is there any solution?

the environment
OS : ubuntu20.04
runtime: containerd:1.6.4
k8s : v1.23.7
N/W : calico:3.23.1

Pod status Running
---------------------------------------------
root@k8s:/tmp# kubectl get all -n kubeshark
NAME                                    READY   STATUS    RESTARTS   AGE
pod/kubeshark-front                     1/1     Running   0          15m
pod/kubeshark-hub                       1/1     Running   0          15m
pod/kubeshark-worker-daemon-set-82h2v   1/1     Running   0          15m
pod/kubeshark-worker-daemon-set-fzd44   1/1     Running   0          15m
pod/kubeshark-worker-daemon-set-hjzs5   1/1     Running   0          15m
pod/kubeshark-worker-daemon-set-qdswh   1/1     Running   0          15m
pod/kubeshark-worker-daemon-set-w74ss   1/1     Running   0          15m
---------------------------------------------

kubeshark debug
----------------------------------------------------
<img width="1480" alt="스크린샷 2023-01-25 오후 4 13 46" src="https://user-images.githubusercontent.com/83107898/214502429-6060b1ee-c6c8-4ff1-8b10-581757d8491a.png">

hub logs
--------------------------------------------------
<img width="1405" alt="스크린샷 2023-01-25 오후 4 13 23" src="https://user-images.githubusercontent.com/83107898/214503064-c719acfd-ba04-48ed-9275-c6c6e9c8f4be.png">

thank you

**Comment by alongir** [comment]
@mothercow-dev I'm not sure it relates- I can confirm we see an unstable behavior when running in conjunction with Calico. We are on it.

**Comment by mothercow-dev** [comment]
> @mothercow-dev I'm not sure it relates- I can confirm we see an unstable behavior when running in conjunction with Calico. We are on it.

What network plugin should I use?? (Flannel, Weave, ETC..)

**Comment by alongir** [comment]
I can confirm that at least with Minikube, there is a compatibility issue that is unrelated to Kubeshark. The issue is between the K8s version and the calico CNI. You can read more about it here: https://github.com/kubernetes/minikube/issues/15173. Based on the issue, when I use calico in conjunction with  '--cni=calico -n 2 --kubernetes-version=v1.24.3', all runs well. While we are still investigating this, it seems that these issues are unrelated to Kubeshark.

**Comment by mothercow-dev** [comment]
There is nothing wrong with setting the environment as below
  - kubernetes : v1.24.3
  - flannel

but, Stopping the streaming traffic will cause the connection to drop.

**Comment by mertyildiran** [comment]
> There is nothing wrong with setting the environment as below
> 
> * kubernetes : v1.24.3
> * flannel
> 
> but, Stopping the streaming traffic will cause the connection to drop.

@mothercow-dev the streaming traffic is the connection's itself. That's why connection is dropping and it's normal. If you click the "Play" button or click "Apply" button to apply the filter then connection will re-establish.

Make sure that you tried [the release 38.5](https://github.com/kubeshark/kubeshark/releases/tag/38.5) since we had some fixes along the way. If it still does not work, please provide a minimal, reproducible example with full list of:

- Cluster configuration (like minikube commands, CNI plugins)
- Kubernetes manifests
- Kubeshark commands (preserving order)

So, we can reproduce the whatever issue you're experiencing on your end.

**Comment by lirany1** [comment]
@mertyildiran hi i am using 38.5 version and got the same issue
```
2023-02-23T18:55:36+02:00 INF tapRunner.go:84 > Waiting for the creation of Kubeshark resources...
2023-02-23T18:55:36+02:00 INF createResources.go:110 > Successfully created a pod. pod=kubeshark-hub
2023-02-23T18:55:36+02:00 INF createResources.go:122 > Successfully created a pod. pod=kubeshark-front
2023-02-23T18:55:36+02:00 INF createResources.go:71 > Successfully created a service. service=kubeshark-hub
2023-02-23T18:55:36+02:00 INF createResources.go:78 > Successfully created a service. service=kubeshark-front
2023-02-23T18:55:36+02:00 INF tapRunner.go:160 > Added: pod=kubeshark-hub
2023-02-23T18:55:36+02:00 INF tapRunner.go:240 > Added: pod=kubeshark-front
2023-02-23T18:55:43+02:00 INF proxy.go:29 > Starting proxy... namespace=kubeshark service=kubeshark-hub src-port=8898
2023-02-23T18:55:43+02:00 INF workers.go:32 > Creating the worker DaemonSet...
2023-02-23T18:55:43+02:00 INF workers.go:51 > Successfully created the worker DaemonSet.
2023-02-23T18:55:44+02:00 INF tapRunner.go:402 > Hub is available at: url=http://localhost:8898
2023-02-23T18:55:45+02:00 INF proxy.go:29 > Starting proxy... namespace=kubeshark service=kubeshark-front src-port=8899
2023-02-23T18:55:46+02:00 INF tapRunner.go:418 > Kubeshark is available at: url=http://localhost:8899
```
when the svc are ClusterIP type the UI not responding
i tried to change it to be NodePort
```
[root@node1 ~]# kubectl get svc -n kubeshark                 
NAME              TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
kubeshark-front   NodePort   10.110.106.100   <none>        80:32066/TCP   4m4s
kubeshark-hub     NodePort   10.110.106.138   <none>        80:31104/TCP   4m4s
```

and got the same issue as above
 (hub is down / worker are down)

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+k3s1", GitCommit:"3e250fdbab72d88f7e6aae57446023a0567ffc97", GitTreeState:"clean", BuildDate:"2021-08-19T19:09:53Z", GoV
ersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+k3s1", GitCommit:"3e250fdbab72d88f7e6aae57446023a0567ffc97", GitTreeState:"clean", BuildDate:"2021-08-19T19:09:53Z", GoV
ersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by azamora-zsc** [comment]
The same is happening to me with:
`$ kubeshark version
  39.4`

**Comment by lirany1** [comment]
I tried to use version 37 instead and it works till it failing with this error:
```
[2023-03-20T14:27:54.758+0000] INFO  ▶ Websocket event - Browser socket connected, socket ID: 4 ▶ [1 socket_server_handlers.go:45 WebSocketConnect]
[GIN] 2023/03/20 - 14:27:54 | 200 |      32.419µs |      10.244.0.0 | GET      "/oas/"
panic: interface conversion: interface {} is nil, not string

goroutine 127 [running]:
github.com/kubeshark/kubeshark/tap/extensions/kafka.dissecting.Summarize({0xc000583a68, 0xc000583a00}, 0xc0006640c0)
        /app/tap/extensions/kafka/main.go:117 +0x1074
github.com/kubeshark/kubeshark/agent/pkg/api.(*DefaultEntryStreamerSocketConnector).SendEntry(0xc000c23000, 0xc000185ba0, 0xc0006640c0, 0x1bbbb40)
        /app/agent-build/pkg/api/entry_streamer_socket_connector.go:35 +0x14f
github.com/kubeshark/kubeshark/agent/pkg/api.(*BasenineEntryStreamer).Get.func1(0x7079e6, 0xc000575920)
        /app/agent-build/pkg/api/socket_data_streamer.go:65 +0x227
created by github.com/kubeshark/kubeshark/agent/pkg/api.(*BasenineEntryStreamer).Get
        /app/agent-build/pkg/api/socket_data_streamer.go:93 +0x605
```

**Comment by mertyildiran** [comment]
Please try [version 39.5](https://github.com/kubeshark/kubeshark/releases/tag/39.5) might be related to a bug that's fixed in https://github.com/kubeshark/kubeshark/issues/1323#issuecomment-1484239637.

**Comment by azamora-zsc** [comment]
> Please try [version 39.5](https://github.com/kubeshark/kubeshark/releases/tag/39.5) might be related to a bug that's fixed in [#1323 (comment)](https://github.com/kubeshark/kubeshark/issues/1323#issuecomment-1484239637).

I've tried with the same result. Still not working.

**Comment by lirany1** [comment]
> Please try [version 39.5](https://github.com/kubeshark/kubeshark/releases/tag/39.5) might be related to a bug that's fixed in [#1323 (comment)](https://github.com/kubeshark/kubeshark/issues/1323#issuecomment-1484239637).

Still same issue here
