### ISSUE TITLE
Kubeshark worker running error prompt "no BTF found for kernel version 5.4.210-1.el7.elrepo.x86_64"

### ISSUE THREAD

**Issue by prometheus-tao** [kubeshark/kubeshark#1363]
**Describe the bug**
Kubeshark workder pod can be runing, The front UI prompt error is "TypeError: Failed to fetch" after input filter parameter click apply 

**Provide more information**
Running on  Rancher 3master 3 worker

**To Reproduce**
1. download kubeshark release binary
2. kubeshark tap --proxy-host 0.0.0.0

**Expected behavior**
Front UI show data and don't have promp error

**Logs**
Upload logs:

ERR tracer/tracer.go:264 > stack="*fmt.wrapError field GoCryptoTlsAbi0Read: program go_crypto_tls_abi0_read: apply CO-RE relocations: no BTF found for kernel version 5.4.210-1.el7.elrepo.x86_64: not supported\n/app/tracer/tracer.go:66 (0x1ecec85)\n/app/worker.go:307 (0x1ef3528)\n/app/worker.go:53 (0x1ef15f2)\n/app/main.go:87 (0x1ef0f05)\n/app/main.go:62 (0x1ef0bf7)\n/usr/local/go/src/runtime/proc.go:255 (0x439027)\n/usr/local/go/src/runtime/asm_amd64.s:1581 (0x4683e1)\n"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window10 
 - Web Browser: Google Chrome

**Additional context**

**Comment by mertyildiran** [comment]
@prometheus-tao the error log `no BTF found for kernel version 5.4.210-1.el7.elrepo.x86_64` you see, is I think not related to the issue that you're experiencing. It's related to eBPF (TLS capture). It means that with your Linux kernel version, the TLS capture for Go language does not work. So, try to upgrade your kernel.

I guess you see a toast message `TypeError: Failed to fetch` when you apply a certain filter. What is the exact filter, could you please share it? What are the steps to reproduce this error? Can you share the browser console output? It can simply be a network error between your browser and the [Hub](https://github.com/kubeshark/hub).

**Comment by prometheus-tao** [comment]
@mertyildiran thanks, I will be try to upgrade linux kernel, The chrome browser to access kubeshark-front occured  console error prompt as follow, Kubeshark-front and kubeshark-hub two service port mapping by nodeport, Can't foud 8898 port on kuberenetes service.

[error log]
Failed to fetch
    at EntriesList.tsx:78:5
    at p (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (asyncToGenerator.js:19:12)
    at i (interval.ts:19:11)
(
TafficViewer.tsx:120 WebSocket connection to 'ws://xxx.xx.xxx.xx:8898/ws?session-token=&refresh-token=' failed: 
e
triesList.tsx:78     GET http://xxx.xx.xxx.xx:8898/pcaps/total-size?refresh-token= net::ERR_CONNECTION_REFUSED
(anony

**Comment by mertyildiran** [comment]
> @mertyildiran thanks, I will be try to upgrade linux kernel, The chrome browser to access kubeshark-front occured console error prompt as follow, Kubeshark-front and kubeshark-hub two service port mapping by nodeport, Can't foud 8898 port on kuberenetes service.
> 
> [error log] Failed to fetch at EntriesList.tsx:78:5 at p (regeneratorRuntime.js:44:17) at Generator. (regeneratorRuntime.js:125:22) at Generator.next (regeneratorRuntime.js:69:21) at r (asyncToGenerator.js:3:20) at s (asyncToGenerator.js:22:9) at asyncToGenerator.js:27:7 at new Promise () at Object. (asyncToGenerator.js:19:12) at i (interval.ts:19:11) ( TafficViewer.tsx:120 WebSocket connection to 'ws://xxx.xx.xxx.xx:8898/ws?session-token=&refresh-token=' failed: e triesList.tsx:78 GET http://xxx.xx.xxx.xx:8898/pcaps/total-size?refresh-token= net::ERR_CONNECTION_REFUSED (anony

Did you change anything in `config.yaml` / `kubeshark.yaml`? If so, please share it. Did you set `tap.ingress.enabled` to `true`?

What is the CLI output? Did the CLI succeed on establishing two proxies to those services?

**Comment by prometheus-tao** [comment]
@mertyildiran I haven't changed anything in yaml, Nothing deploy kubeshark by helm, Starting command as follow.
kubeshark tap --proxy-host 0.0.0.0

[kubeshark starting log] 
2023-06-21T17:29:46+08:00 INF tapRunner.go:145 > Targeted pod: tcpdump-6d945cdfcc-7vzht
2023-06-21T17:29:46+08:00 INF tapRunner.go:145 > Targeted pod: web3-69f4995d9d-7mxhj
2023-06-21T17:29:46+08:00 INF tapRunner.go:145 > Targeted pod: web4-8588669475-phrbk
2023-06-21T17:29:46+08:00 INF tapRunner.go:92 > Waiting for the creation of Kubeshark resources...
2023-06-21T17:29:46+08:00 INF createResources.go:103 > Successfully created a pod. pod=kubeshark-hub
2023-06-21T17:29:46+08:00 INF createResources.go:115 > Successfully created a pod. pod=kubeshark-front
2023-06-21T17:29:46+08:00 INF createResources.go:65 > Successfully created a service. service=kubeshark-hub
2023-06-21T17:29:46+08:00 INF createResources.go:71 > Successfully created a service. service=kubeshark-front
2023-06-21T17:29:46+08:00 INF tapRunner.go:176 > Added: pod=kubeshark-hub
2023-06-21T17:29:46+08:00 INF tapRunner.go:267 > Added: pod=kubeshark-front
2023-06-21T17:30:25+08:00 INF proxy.go:29 > Starting proxy... namespace=kubeshark service=kubeshark-hub src-port=8898
2023-06-21T17:30:30+08:00 INF proxy.go:29 > Starting proxy... namespace=kubeshark service=kubeshark-front src-port=8899
2023-06-21T17:30:41+08:00 WRN common.go:34 > Couldn't connect using proxy, stopping proxy and trying to create port-forward... service=kubeshark-hub
2023-06-21T17:30:41+08:00 INF proxy.go:117 > Starting proxy using port-forward method... dst-port=80 namespace=kubeshark pod=kubeshark-hub src-port=8898
2023-06-21T17:30:45+08:00 WRN common.go:34 > Couldn't connect using proxy, stopping proxy and trying to create port-forward... service=kubeshark-front
2023-06-21T17:30:46+08:00 INF proxy.go:117 > Starting proxy using port-forward method... dst-port=80 namespace=kubeshark pod=kubeshark-front src-port=8899
2023-06-21T17:30:46+08:00 INF workers.go:49 > Creating the worker DaemonSet...
2023-06-21T17:30:46+08:00 INF workers.go:68 > Successfully created the worker DaemonSet.
2023-06-21T17:30:46+08:00 INF tapRunner.go:466 > Hub is available at: url=http://localhost:8898
2023-06-21T17:30:51+08:00 INF tapRunner.go:492 > Kubeshark is available at: url=http://localhost:8899
