### ISSUE TITLE
kubeshark-worker-daemon-set tracer restart

### ISSUE THREAD

**Issue by 905839698** [kubeshark/kubeshark#1448]
2023-11-07T09:57:32+08:00 INF tracer/misc/data.go:18 > Set the data directory to: data-dir=data
2023-11-07T09:57:32+08:00 INF tracer/main.go:41 > Starting tracer...
2023-11-07T09:57:32+08:00 INF tracer/tracer.go:39 > Initializing tracer (chunksSize: 409600) (logSize: 4096)
2023-11-07T09:57:32+08:00 INF tracer/tracer.go:53 > Detected Linux kernel version: 5.14.0-284.25.1.el9_2.x86_64
2023-11-07T09:57:32+08:00 ERR tracer/tracer.go:259 > stack="*fmt.wrapError field GoCryptoTlsAbi0Read: program go_crypto_tls_abi0_read: apply CO-RE relocations: can't read types: type id 124: unknown kind: Unknown (19)\n/app/tracer/tracer.go:63 (0x13e7227)\n/app/tracer/main.go:67 (0x13e0cc5)\n/app/tracer/main.go:47 (0x13e0ae6)\n/app/tracer/main.go:37 (0x13e09bf)\n/usr/local/go/src/runtime/proc.go:250 (0x43db12)\n/usr/local/go/src/runtime/asm_amd64.s:1594 (0x46ec61)\n"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13e3d1b]

goroutine 1 [running]:
main.(*tlsPoller).poll(0x0, 0x1965b30?)
	/app/tracer/tls_poller.go:88 +0xbb
main.(*Tracer).Poll(...)
	/app/tracer/tracer.go:97
main.run()
	/app/tracer/main.go:57 +0x192
main.main()
	/app/tracer/main.go:37 +0x4bf

**Comment by alongir** [comment]
Same as this one: https://kubeshark.slack.com/archives/C04BNKU5SNM/p1699012979745509

**Comment by mertyildiran** [comment]
Related to https://github.com/cilium/ebpf/discussions/900

**Comment by mertyildiran** [comment]
Should be fixed with https://github.com/kubeshark/tracer/commit/97199a581c5e7f974273e65948f4215cb11472b3
