### ISSUE TITLE
Back-off restarting failed container tracer in pod kubeshark-worker-daemon-set-fkb7h_default

### ISSUE THREAD

**Issue by Buenbk** [kubeshark/kubeshark#1453]
**The following is the error output of the tracer container. （Ubuntu 18.04.6 LTS）**
# kubectl logs kubeshark-worker-daemon-set-fkb7h -c tracer
2023-11-14T11:36:16Z INF tracer/misc/data.go:18 > Set the data directory to: data-dir=data
2023-11-14T11:36:16Z INF tracer/main.go:41 > Starting tracer...
2023-11-14T11:36:16Z INF tracer/tracer.go:39 > Initializing tracer (chunksSize: 409600) (logSize: 4096)
2023-11-14T11:36:16Z INF tracer/tracer.go:53 > Detected Linux kernel version: 5.4.0-84-generic
2023-11-14T11:36:16Z ERR tracer/tracer.go:259 > stack="*fmt.wrapError field GoCryptoTlsAbi0Read: program go_crypto_tls_abi0_read: apply CO-RE relocations: no BTF found for kernel version 5.4.0-84-generic: not supported\n/app/tracer/tracer.go:63 (0x13e7227)\n/app/tracer/main.go:67 (0x13e0cc5)\n/app/tracer/main.go:47 (0x13e0ae6)\n/app/tracer/main.go:37 (0x13e09bf)\n/usr/local/go/src/runtime/proc.go:250 (0x43db12)\n/usr/local/go/src/runtime/asm_amd64.s:1594 (0x46ec61)\n"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13e3d1b]

goroutine 1 [running]:
main.(*tlsPoller).poll(0x0, 0x1965b30?)
        /app/tracer/tls_poller.go:88 +0xbb
main.(*Tracer).Poll(...)
        /app/tracer/tracer.go:97
main.run()
        /app/tracer/main.go:57 +0x192
main.main()
        /app/tracer/main.go:37 +0x4bf

**Comment by Buenbk** [comment]
Should I use an older version of kubeshark? Would you please provide me with a compatible version number？(For some season it is forbbiden to upgrade my Ubuntu kernel version.)

**Comment by Buenbk** [comment]
![image](https://github.com/kubeshark/kubeshark/assets/82649417/f57feb34-dc14-4260-b74f-a3a05f723a3d)
I downloaded version 41.2, but why does it show version 51.0.27?
`curl -Lo kubeshark https://github.com/kubeshark/kubeshark/releases/download/41.2/kubeshark_linux_amd64 && chmod 755 kubeshark
./kubeshark tap
`

**Comment by Buenbk** [comment]
I have try some older versions, but none of these can be successfully installed in Ubuntu 18.04.6.

**Comment by previousdeveloper** [comment]
+1 do you have any update here?

**Comment by NiXxXel** [comment]
I have a same problem, don’t know what to do.
Kubernetes Version v1.27.4
Kubeshark v51.0.39

**Comment by rajnikhil-netapp** [comment]
+1 any update on this?

**Comment by rathoreshakti7** [comment]
+1 same issue, If any progress please update.
