### ISSUE TITLE
crashloop on k3d/k3s

### ISSUE THREAD

**Issue by machecazzon** [kubeshark/kubeshark#1479]
**Describe the bug**
```
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 3834, [0::/../../../../init ]" pid=3834
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 3859, [0::/../../../../init ]" pid=3859
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 3878, [0::/../../../besteffort/pod63c9854e-8307-4868-9049-4989a7ac7188/c4bb95ffdcf1dcd347634e474da81f085edb832be46eabdb772ee78479cba0ce ]" pid=3878
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 3889, [0::/../../pod7dfc49c7-ba3f-4687-b292-e4934ad417c5/ef85fa6980108b7f6599e399c53f54b1ba079673277c89911cc5870ccd1ac7ee ]" pid=3889
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39263, [0::/../../../../init ]" pid=39263
sniffer 2024-01-13T19:40:12Z INF kubernetes/resolver/target.go:115 > Targeted pod: argo-cd-argocd-dex-server-579cc77d5c-hc688
sniffer 2024-01-13T19:40:12Z INF kubernetes/resolver/target.go:115 > Targeted pod: cert-manager-cainjector-7bb98b6cbc-bjznv
sniffer 2024-01-13T19:40:12Z INF kubernetes/resolver/target.go:115 > Targeted pod: argo-cd-argocd-redis-68d5f85c66-fnxl7
sniffer 2024-01-13T19:40:12Z INF kubernetes/resolver/target.go:115 > Targeted pod: crossplane-rbac-manager-555fb8c49f-hsvrf
sniffer 2024-01-13T19:40:12Z INF kubernetes/resolver/target.go:115 > Targeted pod: argo-cd-argocd-notifications-controller-67b7f84c76-cxs8l
sniffer 2024-01-13T19:40:12Z INF kubernetes/resolver/target.go:115 > Targeted pod: my-external-secrets-568c8f6cb8-8dxk5
sniffer 2024-01-13T19:40:12Z INF kubernetes/resolver/target.go:115 > Targeted pod: svclb-traefik-f03c233c-pm6vx
sniffer 2024-01-13T19:40:12Z INF kubernetes/resolver/target.go:115 > Targeted pod: local-path-provisioner-7b7dc8d6f5-87r7s
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39281, [0::/../../../../init ]" pid=39281
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39311, [0::/../98e8339bc5bc5cbb5e5aa3e8701311e77183d3afea6e76d023641b5afdad4564 ]" pid=39311
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39312, [0::/../../pod34efdece-e4a0-4e61-bd3c-c7f0fc7c92b3/d2f2edfba32ffbc3d3a995c50317879b1fa33594ff77843fa8df8d104bed06ec ]" pid=39312
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39377, [0::/../../../../init ]" pid=39377
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39397, [0::/../../pod27d0f0ee-c5a7-4b17-9f2f-18e5512e68b8/1fdcc32b86432da605942039a0beb6deb5cf72cd4025052549f0940727251a73 ]" pid=39397
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 3947, [0::/../../../besteffort/pod63c9854e-8307-4868-9049-4989a7ac7188/834e3435bb815c50723aac3b329c3981060fb4cbd0ee18a6fae1b790bc14c247 ]" pid=3947
sniffer 2024-01-13T19:40:12Z INF kubernetes/resolver/target.go:115 > Targeted pod: upbound-provider-gcp-0e47e539c1c0-6bdf7d85fb-4czpl
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 3948, [0::/../../pod7dfc49c7-ba3f-4687-b292-e4934ad417c5/aa0652d5b58b5f01744914efec1c44eec35c189573fc5052c5d5c5de689ee314 ]" pid=3948
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39502, [0::/../../pod34efdece-e4a0-4e61-bd3c-c7f0fc7c92b3/424e84c3e9012ed46a167b4781ee9daab361b782cb39234dd9835b8ff176c8e6 ]" pid=39502
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39655, [0::/../../pod27d0f0ee-c5a7-4b17-9f2f-18e5512e68b8/ba74b734ff6ac7b99042915e6a714d66bc3b302839a77136b9fbe3f3ecc48a9a ]" pid=39655
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39680, [0::/../../pod27d0f0ee-c5a7-4b17-9f2f-18e5512e68b8/ba74b734ff6ac7b99042915e6a714d66bc3b302839a77136b9fbe3f3ecc48a9a ]" pid=39680
sniffer 2024-01-13T19:40:12Z INF kubernetes/resolver/target.go:115 > Targeted pod: crossplane-contrib-provider-helm-503c3591121b-85d5f74ffb-d5wzw
sniffer 2024-01-13T19:40:12Z INF kubernetes/resolver/target.go:115 > Targeted pod: crossplane-contrib-provider-kubernetes-fd7ab5be249e-68fb9db7g8z
sniffer 2024-01-13T19:40:12Z INF kubernetes/resolver/target.go:115 > Targeted pod: provider-sql-9bf151ac568a-78879cc788-qbms7
sniffer 2024-01-13T19:40:13Z WRN main.go:136 > error="bad response code: 404"
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39681, [0::/../../pod27d0f0ee-c5a7-4b17-9f2f-18e5512e68b8/ba74b734ff6ac7b99042915e6a714d66bc3b302839a77136b9fbe3f3ecc48a9a ]" pid=39681
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39682, [0::/../../pod27d0f0ee-c5a7-4b17-9f2f-18e5512e68b8/ba74b734ff6ac7b99042915e6a714d66bc3b302839a77136b9fbe3f3ecc48a9a ]" pid=39682
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39683, [0::/../../pod27d0f0ee-c5a7-4b17-9f2f-18e5512e68b8/ba74b734ff6ac7b99042915e6a714d66bc3b302839a77136b9fbe3f3ecc48a9a ]" pid=39683
sniffer 2024-01-13T19:40:13Z INF assemblers/tcp_streams_map.go:75 > Using 1000 ms as the close timed out TCP stream channels interval
sniffer 2024-01-13T19:40:13Z WRN source/tcp_packet_source.go:88 > Can't use PF_RING socket error="pfring NewRing error: address family not supported by protocol"
sniffer 2024-01-13T19:40:13Z INF source/tcp_packet_source.go:103 > Using AF_PACKET socket as the capture source
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39684, [0::/../../pod27d0f0ee-c5a7-4b17-9f2f-18e5512e68b8/ba74b734ff6ac7b99042915e6a714d66bc3b302839a77136b9fbe3f3ecc48a9a ]" pid=39684
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39685, [0::/../../pod27d0f0ee-c5a7-4b17-9f2f-18e5512e68b8/ba74b734ff6ac7b99042915e6a714d66bc3b302839a77136b9fbe3f3ecc48a9a ]" pid=39685
sniffer 2024-01-13T19:40:13Z INF server/server.go:63 > Starting the server... port=30001
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39686, [0::/../../pod27d0f0ee-c5a7-4b17-9f2f-18e5512e68b8/ba74b734ff6ac7b99042915e6a714d66bc3b302839a77136b9fbe3f3ecc48a9a ]" pid=39686
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39687, [0::/../../pod27d0f0ee-c5a7-4b17-9f2f-18e5512e68b8/ba74b734ff6ac7b99042915e6a714d66bc3b302839a77136b9fbe3f3ecc48a9a ]" pid=39687
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39688, [0::/../../pod27d0f0ee-c5a7-4b17-9f2f-18e5512e68b8/ba74b734ff6ac7b99042915e6a714d66bc3b302839a77136b9fbe3f3ecc48a9a ]" pid=39688
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39689, [0::/../../pod27d0f0ee-c5a7-4b17-9f2f-18e5512e68b8/ba74b734ff6ac7b99042915e6a714d66bc3b302839a77136b9fbe3f3ecc48a9a ]" pid=39689
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 3972, [0::/../../../besteffort/pod63c9854e-8307-4868-9049-4989a7ac7188/834e3435bb815c50723aac3b329c3981060fb4cbd0ee18a6fae1b790bc14c247 ]" pid=3972
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39776, [0::/../7f649d217b734c885e2602dee9d8495d5f7d09971622a0982357e61d7bd07464 ]" pid=39776
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 39984, [0::/ ]" pid=39984
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4001, [0::/../../pod7dfc49c7-ba3f-4687-b292-e4934ad417c5/ee045c41400a22ffbcf29a57261696cb2de8da9fa48838ef455c2bbbb7287234 ]" pid=4001
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4090, [0::/../../../../init ]" pid=4090
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4110, [0::/../../pod0da6c004-77e5-45e3-8a26-96f8b982352e/fd26aff6bb58529a2c76ad39256362b1fb74db3210467884b7c94b029b0f7858 ]" pid=4110
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4144, [0::/../../poddd8603a6-fa41-41bf-becf-848b4e72dcc7/5b769cae3157d2031b79967f25a46ee77dc98e09c7270a74d76eba8e7ab8142a ]" pid=4144
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4175, [0::/../../pod0da6c004-77e5-45e3-8a26-96f8b982352e/df2a649b65067507b10c99b59454e8f594945f2155897fac3c2d4766d7a8002a ]" pid=4175
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4340, [0::/../../../../init ]" pid=4340
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4345, [0::/../../../../init ]" pid=4345
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4381, [0::/../../../besteffort/pod3e00d564-7949-4e05-b1f8-b0093a93377b/5a7dd03c3688a860babb535bb288cb33b6750e0ab05744e98803a870b654e54c ]" pid=4381
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4390, [0::/../../../besteffort/podc474b058-9764-472b-96e6-0da9041c5aaf/dfe8240b14e416d3f459d1b6fbf1c24dd7c1ba2ae100b4d7e642f585600b20e6 ]" pid=4390
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4452, [0::/../../../besteffort/podc474b058-9764-472b-96e6-0da9041c5aaf/ef8b0660f64bb9512e45593b90290877ee0530ba6a47258e151a3a66d136b52a ]" pid=4452
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4476, [0::/../../../besteffort/podc474b058-9764-472b-96e6-0da9041c5aaf/ef8b0660f64bb9512e45593b90290877ee0530ba6a47258e151a3a66d136b52a ]" pid=4476
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4736, [0::/../../../../init ]" pid=4736
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4756, [0::/../../../besteffort/pod24890fd2-321f-458f-856c-4c4cf53a36fe/13ec5cf5fbd111dbfac5afabce3bede51db38d730c0e79e85d2c707819228eb2 ]" pid=4756
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4785, [0::/../../../besteffort/pod24890fd2-321f-458f-856c-4c4cf53a36fe/a7ca40e87c542fa8264237119cb43df0d8ddad5f8bd61ca8a4808dcc2a83d9b2 ]" pid=4785
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4852, [0::/../../../besteffort/pod3e00d564-7949-4e05-b1f8-b0093a93377b/9fadf0ffe0db6618197263111a7d9fb4af8ad13a97fd54ceccdd315f7e2107fb ]" pid=4852
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4867, [0::/../../../besteffort/pod3e00d564-7949-4e05-b1f8-b0093a93377b/9fadf0ffe0db6618197263111a7d9fb4af8ad13a97fd54ceccdd315f7e2107fb ]" pid=4867
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 4876, [0::/../../../besteffort/pod3e00d564-7949-4e05-b1f8-b0093a93377b/9fadf0ffe0db6618197263111a7d9fb4af8ad13a97fd54ceccdd315f7e2107fb ]" pid=4876
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 5145, [0::/../../pod4a53b0e3-3cd6-42a4-b6a8-50ecb7d4b4d6/ec03b50b9301c01e1a48bee320569b848dc34183bb0ecb175e137ea0988814b3 ]" pid=5145
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 56, [0::/../../../../init ]" pid=56
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 6240, [0::/../../../besteffort/podeb76550f-9ebe-4c15-92fb-f337535eeb9f/86e066c951152ec8c638abf203aaab73f88f3e7aac791038adc5f6aeb153904f ]" pid=6240
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 6252, [0::/../../../besteffort/podeb76550f-9ebe-4c15-92fb-f337535eeb9f/86e066c951152ec8c638abf203aaab73f88f3e7aac791038adc5f6aeb153904f ]" pid=6252
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 7, [0::/../../../../k3s ]" pid=7
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 726, [0::/../../../../init ]" pid=726
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 755, [0::/../../../besteffort/pod6e4af37a-eba6-4681-8ca8-8fb7e67bb62a/ed506bd9db6917b257e1b803b6560cf5fc95cc13a5058792ae8bfa4828e6a149 ]" pid=755
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 872, [0::/../../../besteffort/pod6e4af37a-eba6-4681-8ca8-8fb7e67bb62a/69e55ca2ff87cee050261e047a90ead8382689389c8e0608cff6b8c7e929be21 ]" pid=872
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 8903, [0::/../../../besteffort/pod7ada9eed-3c50-4cff-a294-4af562a2c499/d28566c4371a87af16c5183346646340702571142041e4182283356b754b9b58 ]" pid=8903
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 9246, [0::/../../../../init ]" pid=9246
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 9266, [0::/../../../besteffort/pod52cb3b75-f719-4a47-96e7-453ddfec4685/0a84e4136d34af3d6a40b5e260974574273bab369297d04c66b89ad68722173e ]" pid=9266
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 9295, [0::/../../../besteffort/pod52cb3b75-f719-4a47-96e7-453ddfec4685/dcdc7198523f9d31d5bf3d11698f32a33c9eae10923246c2558f36aa32681d6b ]" pid=9295
tracer 2024-01-13T19:40:34Z WRN tracer/tls_process_discoverer.go:69 > Couldn't get the cgroup of process. error="Cgroup path not found for 971, [0::/../../../besteffort/pod6e4af37a-eba6-4681-8ca8-8fb7e67bb62a/3dc1b1fccb241e0cdfff6115dcbe3819e9d21040c20fcfef6d6c70b5a8a4796c ]" pid=971
tracer 2024-01-13T19:40:34Z INF tracer/tls_process_discoverer.go:30 > pids=[]
tracer 2024-01-13T19:40:34Z ERR tracer/tracer.go:259 > stack="*errors.errorString neither debugfs nor tracefs are mounted\n/app/tracer/syscall_hooks.go:25 (0x13059ac)\n/app/tracer/tracer.go:68 (0x1309ae8)\n/app/tracer/main.go:74 (0x1303d80)\n/app/tracer/main.go:61 (0x1303be8)\n/app/tracer/main.go:38 (0x1303a24)\n/usr/local/go/src/runtime/internal/atomic/types.go:194 (0x43aca0)\n/usr/local/go/src/runtime/asm_arm64.s:1172 (0x46c6d4)\n"
tracer 2024-01-13T19:40:34Z INF tracer/bpf_logger.go:58 > Start polling for bpf logs
tracer panic: runtime error: invalid memory address or nil pointer dereference
tracer [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1306ba4]
tracer 
tracer goroutine 1 [running]:
tracer main.(*tlsPoller).poll(0x0, 0x0?)
tracer     /app/tracer/tls_poller.go:88 +0x94
tracer main.(*Tracer).Poll(...)
tracer     /app/tracer/tracer.go:97
tracer main.run()
tracer     /app/tracer/main.go:64 +0x1f8
tracer main.main()
tracer     /app/tracer/main.go:38 +0x414
tracer panic: runtime error: invalid memory address or nil pointer dereference
tracer [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1300b40]
tracer 
tracer goroutine 51 [running]:
tracer main.(*bpfLogger).poll(0x0)
tracer     /app/tracer/bpf_logger.go:61 +0x50
tracer main.(*Tracer).PollForLogging(0x0?)
tracer     /app/tracer/tracer.go:101 +0x20
tracer created by main.run
tracer     /app/tracer/main.go:63 +0x1e4
Stream closed EOF for default/kubeshark-worker-daemon-set-c296v (tracer)
```

**Provide more information**
Running on k3d/k3s

**To Reproduce**
helm install kubeshark kubeshark/kubeshark

check pod logs

**Expected behavior**
works OOTB

**Logs**
see above

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Web Browser: [e.g. Google Chrome]

**Additional context**

```
Name:             kubeshark-worker-daemon-set-c296v
Namespace:        default
Priority:         0
Service Account:  kubeshark-service-account
Node:             k3d-crossplane-local-new-server-0/172.24.0.3
Start Time:       Sat, 13 Jan 2024 20:39:44 +0100
Labels:           app.kubernetes.io/instance=kubeshark
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=kubeshark
                  app.kubernetes.io/version=52.0.0
                  app.kubeshark.co/app=worker
                  controller-revision-hash=65c59cf6df
                  helm.sh/chart=kubeshark-52.0.0
                  pod-template-generation=1
Annotations:      <none>
Status:           Running
IP:               172.24.0.3
IPs:
  IP:           172.24.0.3
Controlled By:  DaemonSet/kubeshark-worker-daemon-set
Containers:
  sniffer:
    Container ID:  containerd://7f649d217b734c885e2602dee9d8495d5f7d09971622a0982357e61d7bd07464
    Image:         docker.io/kubeshark/worker:v52.0.0
    Image ID:      docker.io/kubeshark/worker@sha256:8f77a9620980c11062783f8aec0a1e3bf98ecd1bf20a026feac4dae2dd371a4f
    Port:          <none>
    Host Port:     <none>
    Command:
      ./worker
      -i
      any
      -port
      30001
      -servicemesh
      -procfs
      /hostproc
    State:          Running
      Started:      Sat, 13 Jan 2024 20:40:12 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     750m
      memory:  1Gi
    Requests:
      cpu:      50m
      memory:   50Mi
    Liveness:   tcp-socket :30001 delay=5s timeout=1s period=1s #success=1 #failure=3
    Readiness:  tcp-socket :30001 delay=5s timeout=1s period=1s #success=1 #failure=3
    Environment:
      POD_NAME:       kubeshark-worker-daemon-set-c296v (v1:metadata.name)
      POD_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /app/data from data (rw)
      /hostproc from proc (ro)
      /sys from sys (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tvj88 (ro)
  tracer:
    Container ID:  containerd://7f2a2730c19154d3596e76d4ab741bd688dc183f40747a6c61ebd72741f9460c
    Image:         docker.io/kubeshark/worker:v52.0.0
    Image ID:      docker.io/kubeshark/worker@sha256:8f77a9620980c11062783f8aec0a1e3bf98ecd1bf20a026feac4dae2dd371a4f
    Port:          <none>
    Host Port:     <none>
    Command:
      ./tracer
      -procfs
      /hostproc
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sat, 13 Jan 2024 20:45:57 +0100
      Finished:     Sat, 13 Jan 2024 20:45:57 +0100
    Ready:          False
    Restart Count:  6
    Environment:
      POD_NAME:       kubeshark-worker-daemon-set-c296v (v1:metadata.name)
      POD_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /app/data from data (rw)
      /hostproc from proc (ro)
      /sys from sys (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-tvj88 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:  
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  
  data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  500Mi
  kube-api-access-tvj88:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 :NoExecute op=Exists
                             :NoSchedule op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  10m                    default-scheduler  Successfully assigned default/kubeshark-worker-daemon-set-c296v to k3d-crossplane-local-new-server-0
  Normal   Pulling    10m                    kubelet            Pulling image "docker.io/kubeshark/worker:v52.0.0"
  Normal   Pulled     9m45s                  kubelet            Successfully pulled image "docker.io/kubeshark/worker:v52.0.0" in 27.131506762s
  Normal   Created    9m45s                  kubelet            Created container sniffer
  Normal   Started    9m45s                  kubelet            Started container sniffer
  Normal   Pulled     9m44s                  kubelet            Successfully pulled image "docker.io/kubeshark/worker:v52.0.0" in 1.210949959s
  Normal   Pulled     9m42s                  kubelet            Successfully pulled image "docker.io/kubeshark/worker:v52.0.0" in 1.064176293s
  Normal   Pulled     9m23s                  kubelet            Successfully pulled image "docker.io/kubeshark/worker:v52.0.0" in 1.250261501s
  Normal   Pulling    8m54s (x4 over 9m45s)  kubelet            Pulling image "docker.io/kubeshark/worker:v52.0.0"
  Normal   Pulled     8m53s                  kubelet            Successfully pulled image "docker.io/kubeshark/worker:v52.0.0" in 1.599267542s
  Normal   Created    8m53s (x4 over 9m44s)  kubelet            Created container tracer
  Normal   Started    8m53s (x4 over 9m44s)  kubelet            Started container tracer
  Warning  BackOff    11s (x45 over 9m41s)   kubelet            Back-off restarting failed container
```

**Comment by alongir** [comment]
@machecazzon can you try this release: https://github.com/kubeshark/kubeshark/releases/tag/v52.1.50 ? While we haven't tried this on K3s, issues are likely to be resolved in the latest release.

**Comment by alongir** [comment]
Fixed with https://github.com/kubeshark/kubeshark/releases/tag/v52.3.84
