### ISSUE TITLE
Front crashes

### ISSUE THREAD

**Issue by alongir** [kubeshark/kubeshark#1574]
I installed kubeshark version v52.3.69 mackbook pro and when an execute kubeshark tap I am getting this error from kubeshark-front pod

  Provided flags:
    --config-name = ./runtime-env.js
    --env-file = ./.env

  Your environment variables will be available on 'window.__RUNTIME_CONFIG__'

./runtime-env.js does not exist. Creating one...
Error creating ./runtime-env.js: Error: Error getting 'REACT_APP_AUTH_ENABLED' from process.env
    at /usr/local/lib/node_modules/runtime-env-cra/lib/index.js:45:13

[Slack Message](https://kubeshark.slack.com/archives/C04BNKU5SNM/p1722028372435989?thread_ts=1722028372.435989&cid=C04BNKU5SNM)

**Comment by lingxiao26** [comment]
I encountered the same problem

**Comment by tiptophelmet** [comment]
> I encountered the same problem

Hi @lingxiao26!

:handshake: Thanks for reporting the issue!

1. Don't you mind me asking about dependent helm values? (they are used to form `REACT_APP_AUTH_ENABLED` front env)

:memo: The following info would be appreciated:
- `cloudLicenseEnabled` --> specify if this field is present & provide its value
- `license`                          --> specify if this field is present (**DON'T** provide the value)
- `tap.auth.enabled`        --> specify if this field is present & provide its value

2. Specify the way you have installed Kubeshark v52.3.69
- CLI
- Helm

Thanks!

---

:speech_balloon: Feel free to reach me out in Slack:
https://kubeshark.slack.com/team/U060X1YCMDY

**Comment by tiptophelmet** [comment]
@lingxiao26 

Thank you for the screenshot!

:label: **v52.3.69** requires having `tap.replayDisabled: true` in helm values.yaml specified.

Once you put it in place & apply values.yaml again - this error should be gone.

Let me know if it works :ok_hand: 

Reach out in case any other issues arise!

**Comment by tiptophelmet** [comment]
**PR:**
- https://github.com/kubeshark/kubeshark/pull/1578

**Comment by subhadipb-t** [comment]
@tiptophelmet I'm facing something similar for my front pod also.
I've installed using helm and using 52.2.1

Your environment variables will be available on 'window.__RUNTIME_CONFIG__'

```
./runtime-env.js does not exist. Creating one...
Error creating ./runtime-env.js: Error: Error getting 'REACT_APP_BPF_OVERRIDE_DISABLED' from process.env
at /usr/local/lib/node_modules/runtime-env-cra/lib/index.js:45:13
```

**Comment by tiptophelmet** [comment]
> @tiptophelmet I'm facing something similar for my front pod also.
> I've installed using helm and using 52.2.1
> 
> 
> 
> ```
> Your environment variables will be available on 'window.__RUNTIME_CONFIG__'
> ./runtime-env.js does not exist. Creating one...
> Error creating ./runtime-env.js: Error: Error getting 'REACT_APP_BPF_OVERRIDE_DISABLED' from process.env
> at /usr/local/lib/node_modules/runtime-env-cra/lib/index.js:45:13
> ```

Hi @subhadipb-t !

Please, make sure you have `tap.packetCapture: best` set in your `values.yaml`, before running `helm install`

Let me know if it helps 👌

Thanks!

**Comment by subhadipb-t** [comment]
Thanks for replying.
I tried reinstalling with below values file.

```
config: {}
dumplogs: false
headless: false
kube:
  configpath: ""
  context: ""
license: ""
logs:
  file: ""
manifests:
  dump: false
scripting:
  env: null
  source: ""
  watchScripts: true
tap:
  annotations: {}
  debug: false
  docker:
    imagepullpolicy: Always
    imagepullsecrets: null
    registry: docker.io/kubeshark
    tag: latest
  dryrun: false
  ignoretainted: false
  ingress:
    auth:
      approveddomains: []
    certmanager: letsencrypt-prod
    classname: kubeshark-ingress-class
    controller: k8s.io/ingress-nginx
    enabled: false
    host: ks.svc.cluster.local
    tls: null
  labels: {}
  namespaces:
  - production
  nodeselectorterms: []
  packetCapture: best
  packetcapture: libpcap
  pcap: ""
  persistentstorage: false
  proxy:
    front:
      port: 8899
      srvport: 8899
    host: 0.0.0.0
    hub:
      port: 8898
      srvport: 8898
    worker:
      srvport: 8897
  regex: (someapp)
  release:
    name: kubeshark
    namespace: default
    repo: https://helm.kubeshark.co
  resources:
    hub:
      limits:
        cpu: 750m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 50Mi
    worker:
      limits:
        cpu: 750m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 50Mi
  servicemesh: true
  storageclass: standard
  storagelimit: 200Mi
  tls: true
```

But it's still crashing with above error.
I'm using eks 1.29.
Not sure if some other variable needs to setup.

**Comment by tiptophelmet** [comment]
@subhadipb-t 

Let me validate your helm values 👌

I will reach back & show what's missing.

Meanwhile, use our latest released helm values to use Kubeshark - it is fully compatible with the latest release:
https://github.com/kubeshark/kubeshark/blob/master/helm-chart%2Fvalues.yaml

**Comment by tiptophelmet** [comment]
@subhadipb-t 

While check is in progress, please consider upgrading to the latest v52.3.90. 

Also, consider [installing Kubeshark via CLI](https://docs.kubeshark.co/en/install) - user-friendly command line experience for booting up traffic observation/inspection.

Please, note:
v52.2.1 is far behind & the latest release contains numerous bug fixes, features (even more accurate traffic capturing, better traffic streaming, new Scripting UI, etc.) & performance improvements.

**Comment by subhadipb-t** [comment]
@tiptophelmet seems like after upgrading to latest version it is working well. Though default resource quotas were bit high but I adjusted them.
Thanks a lot for all the help 🙏

**Comment by tiptophelmet** [comment]
> @tiptophelmet seems like after upgrading to latest version it is working well. Though default resource quotas were bit high but I adjusted them.
> Thanks a lot for all the help 🙏 

@subhadipb-t I am happy you found the latest release useful!

Feel free to reach us in any case!

Happy traffic monitoring 👌

More features are coming to Kubeshark in the future!
